[KARAF-3996] Update karaf script to be able to use custom MAX_FD

diff --git a/assemblies/apache-karaf/src/main/distribution/unix-shell/bin/karaf b/assemblies/apache-karaf/src/main/distribution/unix-shell/bin/karaf
--- a/assemblies/apache-karaf/src/main/distribution/unix-shell/bin/karaf
+++ b/assemblies/apache-karaf/src/main/distribution/unix-shell/bin/karaf
@@ -91,24 +91,22 @@ unlimitFD() {
 
     # Increase the maximum file descriptors if we can
     if [ "$os400" = "false" ] && [ "$cygwin" = "false" ]; then
-        MAX_FD_LIMIT=`ulimit -H -n`
-        if [ "$MAX_FD_LIMIT" != 'unlimited' ]; then 
+        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+            MAX_FD_LIMIT=`ulimit -H -n`
             if [ $? -eq 0 ]; then
-                if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-                    # use the system max
-                    MAX_FD="$MAX_FD_LIMIT"
-                fi
-
-                ulimit -n $MAX_FD > /dev/null
-                # echo "ulimit -n" `ulimit -n`
-                if [ $? -ne 0 ]; then
-                    warn "Could not set maximum file descriptor limit: $MAX_FD"
-                fi
+                # use the system max
+                MAX_FD="$MAX_FD_LIMIT"
             else
                 warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
             fi
         fi
-    fi
+        if [ "$MAX_FD" != 'unlimited' ]; then
+            ulimit -n $MAX_FD > /dev/null
+            if [ $? -ne 0 ]; then
+                warn "Could not set maximum file descriptor limit: $MAX_FD"
+            fi
+        fi
+     fi
 }
 
 locateHome() {
