SMX4KNL-48 - ulimit error on MacOS X Leopard 10.5.
git-svn-id: https://svn.apache.org/repos/asf/servicemix/smx4/kernel/trunk@661431 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/assembly/src/main/distribution/unix-shell/bin/servicemix b/assembly/src/main/distribution/unix-shell/bin/servicemix
--- a/assembly/src/main/distribution/unix-shell/bin/servicemix
+++ b/assembly/src/main/distribution/unix-shell/bin/servicemix
@@ -88,19 +88,21 @@ unlimitFD() {
     # Increase the maximum file descriptors if we can
     if [ "$os400" = "false" ] && [ "$cygwin" = "false" ]; then
         MAX_FD_LIMIT=`ulimit -H -n`
-        if [ $? -eq 0 ]; then
-            if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-                # use the system max
-                MAX_FD="$MAX_FD_LIMIT"
-            fi
+        if [ "$MAX_FD_LIMIT" != 'unlimited' ]; then 
+            if [ $? -eq 0 ]; then
+                if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+                    # use the system max
+                    MAX_FD="$MAX_FD_LIMIT"
+                fi
 
-            ulimit -n $MAX_FD > /dev/null
-            # echo "ulimit -n" `ulimit -n`
-            if [ $? -ne 0 ]; then
-                warn "Could not set maximum file descriptor limit: $MAX_FD"
+                ulimit -n $MAX_FD > /dev/null
+                # echo "ulimit -n" `ulimit -n`
+                if [ $? -ne 0 ]; then
+                    warn "Could not set maximum file descriptor limit: $MAX_FD"
+                fi
+            else
+                warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
             fi
-        else
-            warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
         fi
     fi
 }
@@ -118,11 +120,11 @@ locateHome() {
 
 locateBase() {
     if [ "x$SERVICEMIX_BASE" != "x" ]; then
-    	if [ ! -d "$SERVICEMIX_BASE" ]; then
-        	die "SERVICEMIX_BASE is not valid: $SERVICEMIX_BASE"
-    	fi
-	else
-	    SERVICEMIX_BASE=$SERVICEMIX_HOME
+        if [ ! -d "$SERVICEMIX_BASE" ]; then
+            die "SERVICEMIX_BASE is not valid: $SERVICEMIX_BASE"
+        fi
+    else
+        SERVICEMIX_BASE=$SERVICEMIX_HOME
     fi
 }
 
